name: Jira Integration

on:
  create:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - closed

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira ID
        id: extract
        run: |
          if [[ "${{ github.event_name }}" == "create" ]]; then
            # Extraer ID de Jira del nombre de la branch
            BRANCH_NAME="${{ github.ref_name }}"
            JIRA_ID=$(echo $BRANCH_NAME | grep -o 'PIC-[0-9]\+' || echo '')
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Extraer ID de Jira del título del PR
            PR_TITLE="${{ github.event.pull_request.title }}"
            JIRA_ID=$(echo $PR_TITLE | grep -o 'PIC-[0-9]\+' || echo '')
          fi
          echo "JIRA_ID=$JIRA_ID" >> $GITHUB_OUTPUT

      - name: Update Jira Status
        if: steps.extract.outputs.JIRA_ID != ''
        run: |
          if [[ "${{ github.event_name }}" == "create" ]]; then
            # Mover a "In Progress"
            curl -X POST "https://dev-sync-clg49o5ck-santiago-bianuccis-projects.vercel.app/jira/issue/${{ steps.extract.outputs.JIRA_ID }}/transition" \
              -H "Content-Type: application/json" \
              -d '{"status_id": "31"}'
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "opened" ]]; then
            # Mover a "In Review"
            curl -X POST "https://dev-sync-clg49o5ck-santiago-bianuccis-projects.vercel.app/jira/issue/${{ steps.extract.outputs.JIRA_ID }}/transition" \
              -H "Content-Type: application/json" \
              -d '{"status_id": "41"}'
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            # Mover a "Completed"
            curl -X POST "https://dev-sync-clg49o5ck-santiago-bianuccis-projects.vercel.app/jira/issue/${{ steps.extract.outputs.JIRA_ID }}/transition" \
              -H "Content-Type: application/json" \
              -d '{"status_id": "51"}'
          fi
